### ISSUE TITLE
Cannot catch "Feature Extract" node error

### ISSUE THREAD

**Issue by adasilva70** [node-red/node-red-bluemix-nodes#28]
I am using the "Feature Extract" node and when I reach my daily limits I can see the following error in the logs:

OUT 8 Dec 14:17:38 - [error] [alchemy-feature-extract:12082910.edf7d7] Alchemy API request error: daily-transaction-limit-exceeded

But I don't catch this error in the Catch node. I believe the second argument (msg) is missing when sending this error with node.error function.

**Comment by mnery9** [comment]
Indeed. I've tried this too and none of the "Status" or "Catch" node produce a message when the "Alchemy Feature Extract" node gives the error. I was using this Alchemy API node in part of a flow handling HTTP requests, but since I am not able to handle this error condition, sometimes I would not be able to make my "http response" to output something in response to the http request. I am now using only the Watson Concept Insights node, but I'd like to use these two APIs for concept extraction.  Thanks,

**Comment by knolleary** [comment]
Thanks for raising; as you've discovered, these nodes haven't been updated since the additional of the Catch/Status nodes. Will get that done as soon as we can.
